"""teste de migração

Revision ID: fc52f52f6ed8
Revises: 25e9cf188f41
Create Date: 2025-10-06 19:47:30.768245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc52f52f6ed8'
down_revision = '25e9cf188f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=255), nullable=False),
    sa.Column('titulo_nacional', sa.String(length=255), nullable=False),
    sa.Column('ano_lancamento', sa.Integer(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('sinopse', sa.String(length=255), nullable=False),
    sa.Column('orcamento', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('faturamentoLancamento', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('posterPrincipal', sa.String(), nullable=False),
    sa.Column('linkTrailer', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcaoTecnica',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genero',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sexo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filmeGenero',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generoPrincipal', sa.Boolean(), nullable=False),
    sa.Column('idFilme', sa.Integer(), nullable=False),
    sa.Column('idGenero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idFilme'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['idGenero'], ['genero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nacionalidade', sa.String(length=255), nullable=False),
    sa.Column('dataNascimento', mysql.DATETIME(), nullable=False),
    sa.Column('biografia', sa.String(length=255), nullable=False),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('idSexo', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['idSexo'], ['sexo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nomeArtistico', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('nomeArtistico')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nota', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('dataAvaliacao', mysql.DATETIME(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.Column('recomenda', sa.Boolean(), nullable=False),
    sa.Column('idFilme', sa.Integer(), nullable=False),
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idFilme'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inicioTrabalho', mysql.DATETIME(), nullable=False),
    sa.Column('fimTranalho', mysql.DATETIME(), nullable=False),
    sa.Column('remuneracao', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.String(length=100), nullable=False),
    sa.Column('idPessoa', sa.Uuid(), nullable=False),
    sa.Column('idFilme', sa.Uuid(), nullable=False),
    sa.Column('idFuncaoTecnica', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['idFilme'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['idFuncaoTecnica'], ['funcaoTecnica.id'], ),
    sa.ForeignKeyConstraint(['idPessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atuacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('papel', sa.String(length=100), nullable=False),
    sa.Column('protagonista', sa.Boolean(), nullable=False),
    sa.Column('creditado', sa.Boolean(), nullable=False),
    sa.Column('cache', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tempoTela', sa.Integer(), nullable=False),
    sa.Column('idAtor', sa.Uuid(), nullable=False),
    sa.Column('idFilme', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['idAtor'], ['ator.id'], ),
    sa.ForeignKeyConstraint(['idFilme'], ['filmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('usa_2fa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('usa_2fa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    op.drop_table('atuacao')
    op.drop_table('participacao')
    op.drop_table('avaliacoes')
    op.drop_table('ator')
    op.drop_table('pessoa')
    op.drop_table('filmeGenero')
    op.drop_table('sexo')
    op.drop_table('genero')
    op.drop_table('funcaoTecnica')
    op.drop_table('filmes')
    # ### end Alembic commands ###
